import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ELEBLOG',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  // This is the page
  children: React.ReactNode
}) {

  const header = 
  <header>
    <div className='text-center border-b border-slate-200  p-8 my-6'>
      <Image className='mx-auto' src="/favicon.jpg" width={40} height={40}></Image>
      <Link className="text-3xl font-bold bg-amber-50" href="/">
        <h1>ELEDAH</h1>
      </Link>
    </div>
  </header>

  const footer =
  <div className='text-center border-t border-slate-200 mt-6 py-6'>
    <p>!</p>
  </div>

  return (
    // this is the header and the fooder
    <html lang="en" dir='rtl' className='bg-amber-50'>
      <body className={inter.className}>
        <div className='mx-auto md:max-w-2xl lg:max-w-3xl px-6'>
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  )
}
